apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
token: #token#
tokenTTL: 1h
api:
  advertiseAddress: 172.17.8.101
networking:
  # Flannel
  podSubnet: 10.244.0.0/16
featureGates:
  SelfHosting: true
  #StoreCertsInSecrets: true
  HighAvailability: true
apiServerExtraArgs:
  # https://kubernetes.io/docs/reference/generated/kube-apiserver/
  service-node-port-range: 80-32767
  feature-gates: ""
controllerManagerExtraArgs:
  # https://kubernetes.io/docs/reference/generated/kube-controller-manager/
  feature-gates: ""
schedulerExtraArgs:
  # https://kubernetes.io/docs/reference/generated/kube-scheduler/
  feature-gates: ""
