---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: repos-minio
  name: export-repos-minio-2
  namespace: blobs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: minio
  selector:
    matchLabels:
      pod-name: repos-minio-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: export-repos-minio-2
  labels:
    pod-name: repos-minio-2
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio
  local:
    path: /mnt/local-storage/export-repos-minio-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - youkube-01
